package dev.recordish;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Exports recording bookmarks as friendly text and FFmpeg chapter metadata.
 */
public final class ChapterManager {
    private static final Logger LOGGER = Logger.getLogger("Recordish");

    private ChapterManager() {
    }

    public static String formatTimestamp(long millis) {
        long totalSeconds = Math.max(0L, millis) / 1000L;
        long hours = totalSeconds / 3600L;
        long minutes = (totalSeconds % 3600L) / 60L;
        long seconds = totalSeconds % 60L;
        return String.format(
                Locale.ROOT,
                "%02d:%02d:%02d",
                hours,
                minutes,
                seconds);
    }

    /**
     * Writes the V1-0.08 {@code *_chapters.txt} format, suitable for pasting
     * into a video description.
     */
    public static Path writeChapterTextFile(
            Path videoFile,
            List<RecordingBookmark> markers) {
        List<RecordingBookmark> validMarkers = validMarkers(markers);
        if (videoFile == null || validMarkers.isEmpty()) {
            return null;
        }

        Path output = videoFile.resolveSibling(stem(videoFile) + "_chapters.txt");
        List<String> lines = new ArrayList<String>();
        lines.add("Chapters / Markers for: " + filename(videoFile));
        lines.add("Generated by Recordish");
        lines.add("Tip: paste these into a YouTube description for clickable chapters.");
        lines.add("");

        int index = 1;
        for (RecordingBookmark marker : validMarkers) {
            lines.add(formatTimestamp(marker.getTimestampMs())
                    + "  "
                    + safeLabel(marker.getDescription(), index));
            index++;
        }

        try {
            Files.write(
                    output,
                    lines,
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING,
                    StandardOpenOption.WRITE);
            return output;
        } catch (IOException exception) {
            LOGGER.log(Level.WARNING, "Failed to write chapter text file " + output, exception);
            return null;
        }
    }

    /**
     * Writes an {@code FFMETADATA1} sidecar. Every bookmark begins a chapter;
     * its end is the next bookmark, or the supplied recording duration.
     */
    public static Path writeFfmetadataFile(
            Path videoFile,
            List<RecordingBookmark> markers,
            long totalDurationMs) {
        List<RecordingBookmark> validMarkers = validMarkers(markers);
        if (videoFile == null || validMarkers.isEmpty()) {
            return null;
        }

        Path output = videoFile.resolveSibling(stem(videoFile) + "_ffmeta.txt");
        StringBuilder metadata = new StringBuilder();
        metadata.append(";FFMETADATA1\n");

        for (int index = 0; index < validMarkers.size(); index++) {
            RecordingBookmark marker = validMarkers.get(index);
            long start = Math.max(0L, marker.getTimestampMs());
            long end;
            if (index + 1 < validMarkers.size()) {
                end = Math.max(
                        start + 1L,
                        validMarkers.get(index + 1).getTimestampMs());
            } else {
                long requestedEnd = totalDurationMs > 0L
                        ? totalDurationMs
                        : start + 1000L;
                end = Math.max(start + 1L, requestedEnd);
            }

            metadata.append("[CHAPTER]\n");
            metadata.append("TIMEBASE=1/1000\n");
            metadata.append("START=").append(start).append('\n');
            metadata.append("END=").append(end).append('\n');
            metadata.append("title=")
                    .append(escapeMeta(safeLabel(
                            marker.getDescription(),
                            index + 1)))
                    .append('\n');
        }

        try {
            Files.write(
                    output,
                    metadata.toString().getBytes(StandardCharsets.UTF_8),
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING,
                    StandardOpenOption.WRITE);
            return output;
        } catch (IOException exception) {
            LOGGER.log(Level.WARNING, "Failed to write FFmetadata file " + output, exception);
            return null;
        }
    }

    /**
     * Embeds chapters through an FFmpeg stream copy. The source is never
     * replaced or deleted. A protected destination is never overwritten.
     */
    public static Path embedChapters(
            Path videoFile,
            List<RecordingBookmark> markers,
            long totalDurationMs) {
        if (videoFile == null || !Files.isRegularFile(videoFile)) {
            return null;
        }

        Path metadata = writeFfmetadataFile(videoFile, markers, totalDurationMs);
        if (metadata == null) {
            return null;
        }

        RecordishConfig config = RecordishConfig.get();
        String executable = StorageManager.resolveFfmpegExecutable(config);
        if (isBlank(executable)) {
            LOGGER.warning("FFmpeg is unavailable; chapters cannot be embedded.");
            return null;
        }

        String extension = extension(videoFile);
        Path output = videoFile.resolveSibling(stem(videoFile) + "_chaptered" + extension);
        Path temporary = videoFile.resolveSibling(
                stem(videoFile) + "_chaptered.part" + extension);
        if (StorageManager.isProtected(config, output)
                || StorageManager.isProtected(config, temporary)) {
            LOGGER.warning("Refusing to overwrite a protected chapter output: " + output);
            return null;
        }

        try {
            Files.deleteIfExists(temporary);
            List<String> arguments = new ArrayList<String>();
            Collections.addAll(
                    arguments,
                    "-nostdin",
                    "-hide_banner",
                    "-y",
                    "-i", videoFile.toAbsolutePath().toString(),
                    "-i", metadata.toAbsolutePath().toString(),
                    "-map_metadata", "1",
                    "-map_chapters", "1",
                    "-codec", "copy",
                    temporary.toAbsolutePath().toString());

            StorageManager.ProcessResult result = StorageManager.runProcess(
                    StorageManager.createMediaProcess(executable, arguments),
                    2L,
                    TimeUnit.HOURS);
            if (!result.succeeded()
                    || !Files.isRegularFile(temporary)
                    || Files.size(temporary) <= 0L) {
                LOGGER.warning("Chapter embedding failed"
                        + (result.timedOut()
                        ? " (timed out)"
                        : " with exit code " + result.exitCode()));
                Files.deleteIfExists(temporary);
                return null;
            }

            try {
                Files.move(
                        temporary,
                        output,
                        StandardCopyOption.REPLACE_EXISTING,
                        StandardCopyOption.ATOMIC_MOVE);
            } catch (IOException atomicMoveFailure) {
                Files.move(temporary, output, StandardCopyOption.REPLACE_EXISTING);
            }
            VideoMetadata.clearCache();
            return output;
        } catch (Exception exception) {
            LOGGER.log(Level.WARNING, "Failed to embed chapters in " + videoFile, exception);
            try {
                Files.deleteIfExists(temporary);
            } catch (IOException ignored) {
            }
            return null;
        }
    }

    private static List<RecordingBookmark> validMarkers(
            List<RecordingBookmark> markers) {
        if (markers == null || markers.isEmpty()) {
            return Collections.emptyList();
        }
        List<RecordingBookmark> valid = new ArrayList<RecordingBookmark>();
        for (RecordingBookmark marker : markers) {
            if (marker != null) {
                valid.add(marker);
            }
        }
        return valid;
    }

    private static String stem(Path videoFile) {
        String filename = filename(videoFile);
        int dot = filename.lastIndexOf('.');
        return dot > 0 ? filename.substring(0, dot) : filename;
    }

    private static String extension(Path videoFile) {
        String filename = filename(videoFile);
        int dot = filename.lastIndexOf('.');
        return dot > 0 ? filename.substring(dot) : ".mkv";
    }

    private static String filename(Path videoFile) {
        return videoFile == null || videoFile.getFileName() == null
                ? "?"
                : videoFile.getFileName().toString();
    }

    private static String safeLabel(String description, int index) {
        return isBlank(description)
                ? "Chapter " + index
                : description.trim();
    }

    /** Escapes the characters reserved by the FFMETADATA1 grammar. */
    private static String escapeMeta(String value) {
        return value.replace("\\", "\\\\")
                .replace("=", "\\=")
                .replace(";", "\\;")
                .replace("#", "\\#")
                .replace("\r", " ")
                .replace("\n", " ");
    }

    private static boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }
}
